name: NASA PROJECT CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubantu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js version 20
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - run: npm run install-server
      - run: npm run install-client
      - run: npm run build --prefix client
